package com.ifsc.secstor.api.util;

public class Constants {

    public static final String DATA = "data";
    public static final String ATTRIBUTE_CONFIG = "attribute_config";
    public static final String GENERALIZATION_LEVEL = "generalization_level";
    public static final String CLASSIFICATION = "classification";
    public static final String METHOD = "method";
    public static final String GENERALIZATION = "generalization";
    public static final String RANDOMIZATION = "randomization";
    public static final String IDENTIFIER = "identifier";
    public static final String SENSITIVE = "sensitive";
    public static final String QUASI_IDENTIFIER = "quasi-identifier";
    public static final String SHAMIR = "shamir";
    public static final String PSS = "pss";
    public static final String CSS = "css";
    public static final String KRAWCZYK = "krawczyk";
    public static final String PVSS = "pvss";
    public static final String SECRET = "secret";
    public static final String MACKEYS = "macKeys";
    public static final String FINGERPRINTS = "fingerprints";
    public static final String ENCKEYS = "encKeys";
    public static final String MODULUS = "modulus";
    public static final String SHARES = "shares";
    public static final String USERNAME = "username";
    public static final String ID = "id";
    public static final String TOKEN_BEARER = "Bearer ";
    public static final String HASHED_PASSWORD = "Hashed";
    public static final String CLIENT = "client";
    public static final String ADMINISTRATOR = "administrator";
    public static final String REGISTER_TEMPLATE = "register";
    public static final String SUCCESS_TEMPLATE = "success";
    public static final String ERROR_TEMPLATE = "error";
    public static final String ERROR = "error";
    public static final String USER = "user";
    public static final String USERNAMES = "usernames";
    public static final String ROLE = "role";
    public static final String REFRESH_TOKEN = "refresh_token";
    public static final String ACCESS_TOKEN = "access_token";
    public static final String PASSWORD = "password";
    public static final String SHARE = "share";
    public static final String MACKEY = "macKey";
    public static final String INNER_MACKEY = "inner object of macKeys";
    public static final String MAC = "mac";
    public static final String INNER_MAC = "inner object of macs";
    public static final String FINGERPRINT = "fingerprint";
    public static final String ENCKEY = "encKey";
    public static final String PARAMETERS = "parameters";
    public static final String DOYOURBEST = "doYourBest";
    public static final String KEY = "key";
}
